# Defaults
os: linux
dist: focal
language: cpp

jobs:
  include:
    # Native jobs
    - compiler: gcc
    - compiler: clang
    - os: osx
    # emscripten job
    - language: node_js
      node_js: node
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src emscripten/emsdk:latest bash
      script:
        - docker exec -it emscripten bash scripts/build_emscripten.sh

before_install:
  - ./scripts/install_prerequisites.sh -v -u -m "apt-get brew"

script:
  - mkdir build && cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - cmake --build . -j 8
